### PR TITLE
Dir name too long

### LINKED ISSUE #100: Very long URLs cause contribution tool to fail
- [Kindle Direct](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fp2b-compliance-declarations&expertMode=true&language=en_US&name=Kindle%20Direct%20PublishingKDP%20Terms%20and%20Conditions&url=https%3A%2F%2Fkdp-eu.amazon.com%2Fagreement%3Ftoken%3DeyJjbGllbnRJZCI6ImtpbmRsZV9kaXJlY3RfcHVibGlzaGluZyIsImRvY3VtZW50SWQiOiJrZHAiLCJjYW5jZWxVcmwiOiJodHRwczovL2tkcC5hbWF6b24uY29tIiwiY2xpZW50TG9jYWxlIjoiTkEiLCJkaXNwbGF5UGFyYW1zIjpudWxsLCJyYXdQYXJhbXMiOm51bGx9%7CeyJtYXRlcmlhbFNlcmlhbCI6MSwiaG1hYyI6Ik9pRzdzcG1UNm5LY25veWhlVG50cDRSQnBKVHAzQ1dwc2g0VXlDMDJKOW89IiwianNvbkhtYWMiOnRydWUsInR5cGUiOiJSRUFEX09OTFkiLCJhY2NlcHQiOmZhbHNlfQ)

This happens because folder created is too long.

### PR DESCRIPTION
**Pull request by martinratinaud**
Example with [Kindle Direct](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fp2b-compliance-declarations&name=Kindle%20Direct%20PublishingKDP%20Terms%20and%20Conditions&url=https://kdp-eu.amazon.com/agreement?token=eyJjbGllbnRJZCI6ImtpbmRsZV9kaXJlY3RfcHVibGlzaGluZyIsImRvY3VtZW50SWQiOiJrZHAiLCJjYW5jZWxVcmwiOiJodHRwczovL2tkcC5hbWF6b24uY29tIiwiY2xpZW50TG9jYWxlIjoiTkEiLCJkaXNwbGF5UGFyYW1zIjpudWxsLCJyYXdQYXJhbXMiOm51bGx9%7CeyJtYXRlcmlhbFNlcmlhbCI6MSwiaG1hYyI6Ik9pRzdzcG1UNm5LY25veWhlVG50cDRSQnBKVHAzQ1dwc2g0VXlDMDJKOW89IiwianNvbkhtYWMiOnRydWUsInR5cGUiOiJSRUFEX09OTFkiLCJhY2NlcHQiOmZhbHNlfQ&printView=true&language=en_US)

Fixes #100 

The directory name is used to keep downloaded URL in cache.

### CODE REVIEW

File: src/modules/Common/services/open-terms-archive.ts [hunk 1]
```diff
@@ -78,5 +78,33 @@ export const getVersion = async (documentDeclaration: OTADocumentDeclaration, co
   return getVersionFromSnapshot(snapshot);
 };
 
+const cleanStringForFileSystem = (string: string) => string.replace(/[^\p{L}\d_]/gimu, '_');
+
+// In case executeClientScripts is true, ota snapshot fetcher will wait
+// for selector to be found on the page. The resulting snapshot will be
+// different each time a new selector is added.
+// This is the same if language changes
+export const generateAlwaysValidFolderName = (
```
Comment (clementbiron) [inline src/modules/Common/services/open-terms-archive.ts:87]: `generateFolderName` should be enought no ?

**Review by clementbiron — APPROVED** [review]
