### PR TITLE
Do not fail when selector is not found

### LINKED ISSUE #92: Can't select in page `Selector was not found`
- [bol.com](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fp2b-compliance-declarations&documentType=Acceptable%20Use%20Policy&expertMode=true&name=bol.com&url=https%3A%2F%2Fwww.bol.com%2Fbe%2Fnl%2Fm%2Fovereenkomst-verkoper-zakelijk%2F&hiddenCssClass[]=modalWindow)

```
Uncaught Error: Selector was not found.
    at finder (css-path-finder.js:40:11)
    at HTMLBodyElement.onClick (injected-script.js:94:17)
```

### PR DESCRIPTION
**Pull request by martinratinaud**
Fixes #92

### CODE REVIEW

File: public/iframe-selector/injected-script.js [hunk 1]
```diff
@@ -91,7 +91,12 @@ function onMouseLeave(e) {
 }
 
 function onClick(e) {
-  var cssPath = finder(e.target);
+  let cssPath;
+  try {
+    cssPath = finder(e.target);
+  } catch (e) {
+    console.error(e);
```
Comment (MattiSG) [inline public/iframe-selector/injected-script.js:98]: Is this an `error` or a `warn` if we don't consider a reason to fail? 🙂

Comment (martinratinaud) [reply public/iframe-selector/injected-script.js:98]: This is for the log line to stand out of the logs if such a case happen.
I want to be able to see if there are other case when it does not work.

I agree that this should not be considered an error anyway as it's handled so will change to `console.log`

**Review by clementbiron — APPROVED** [review]
